Bibliografia:

[1] Lloyd N. Trefethen, David Bau III, Numerical Linear Algebra, David Bau, https://www.cs.cmu.edu/afs/cs/academic/class/15859n-f16/Handouts/TrefethenBau/ArnoldiIteration-33.pdf

In [13]:
using LinearAlgebra

In [7]:
A = [1,3,4,-2,
     2,-4,-1,2,
     3,5,1,1,
     2,-4,-2,-1]
A = reshape(A,4,4)'

4×4 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1   3   4  -2
 2  -4  -1   2
 3   5   1   1
 2  -4  -2  -1

Algorytm Arnoldiego:
Niech $A_{m\times m}$

b = dowolne o długości $m$, $q_1 = b /||b||$  
for $k=1,2,3,\ldots,n$  
&nbsp;&nbsp;&nbsp;&nbsp;$v=Aq_k$  
&nbsp;&nbsp;&nbsp;&nbsp;for j=1 to n  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$h_{jk}=q_j^{*}v$  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$v=v-h_{jk}q_j$  
&nbsp;&nbsp;&nbsp;&nbsp;$h_{k+1,k} = ||v||$  
&nbsp;&nbsp;&nbsp;&nbsp;$q_{k+1} = v/h_{k+1,k}$

In [59]:
function myarnoldi(A,b=nothing)
    n,m = size(A)
    if b == nothing
        b = rand(m,1)
    end
    Q = zeros(m,n)
    H = zeros(m,n)

    Q[:,1] = b / norm(b)
    for k=1:n
        v = A*Q[:,k]
        for j=1:k
            H[j,k] = Q[:,j]'*v
            v = v - H[j,k]*Q[:,j]
        end
        if k < m
            H[k+1,k] = norm(v)
            Q[:,k+1] = v/H[k+1,k]
        end
    end
    return Q,H
end

myarnoldi (generic function with 2 methods)

In [60]:
Q,H = myarnoldi(A)
display(H)
display(Q)
# sprawdzenie (oczekujemy zero bo A = QHQ', czyli AQ=QH)
norm(A*Q - Q*H)

3×3 Array{Float64,2}:
 10.7228   7.80251  -5.68989e-15
  7.80251  1.15951   1.31026
  0.0      1.31026   2.11765

3×3 Array{Float64,2}:
 0.478685  -0.508101  -0.716026
 0.73785   -0.209201   0.641726
 0.475855   0.835505  -0.274761

1.2212453270876722e-15

In [69]:
A = [1 -1  3
     -1 4 8
     3 8 9]
Q,H = myarnoldi(A,[1;1;1])
display(H)
display(Q)
# sprawdzenie (oczekujemy zero bo A = QHQ', czyli AQ=QH)
norm(A*Q - Q*H)

3×3 Array{Float64,2}:
 11.3333   6.94422  -2.66454e-15
  6.94422  1.80261   2.92533
  0.0      2.92533   0.864055

3×3 Array{Float64,2}:
 0.57735  -0.692842   -0.432014
 0.57735  -0.0277137   0.816026
 0.57735   0.720556   -0.384012

1.3322676295501878e-15